config/routes.rb
Rails.application.routes.draw do

  root :to => 'home#index'

  devise_for :sns_users, controllers: {
    registrations: "sns_users/registrations",
    omniauth_callbacks: "sns_users/omniauth_callbacks"
  }

  #投稿関係
  resources :blogs do
    resources :comments
  end

  #ログイン関係
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {maximum: 30}
  validates :email, presence: true, length: {maximum: 80}, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_save{email.downcase!}
  validates :password, presence: true, length: {minimum: 6}
  has_secure_password

  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  #指定のユーザをフォローする
  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end

  #フォローしているかどうかを確認する
  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  #指定のユーザのフォローを解除する
  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user_infomation, only: [:show, :edit, :update]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path, notice:"新たにユーザー情報を登録しました！"
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "ユーザー情報を編集しました！"
    else
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name,
         :email, :password, :password_confirmation)
    end

    def set_user_infomation
      @user = User.find(params[:id])
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>">
  <% unless current_user == user %>
    <% unless current_user.following?(user) %>
      <%= form_with(model: current_user.active_relationships.new(followed_id: user.id) ) do |f| %>
        <%= f.hidden_field :followed_id %>
        <%= f.submit "フォロー" %>
      <% end %>
    <% else %>
      <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id), method: :delete ) do |f| %>
        <%= f.submit "つながりを解除" %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true,) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <% @user.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    </div>
  <% end %>

  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :email %>
  <%= form.email_field :email %>

  <%= form.label :password %>
  <%= form.password_field :password %>

  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation %>

  <%= form.submit "登録" %>
<% end %>

app/views/users/edit.html.erb
<h2>ユーザー情報を編集</h2>

<%= render 'form' %>

app/views/users/index.html.erb
<h2>ユーザー</h2>
<% @users.each do |user| %>
  <%= user.name %>
  <%= user.email %>
  <%= render 'follow_form', user: user %>
<% end %>

app/views/users/new.html.erb
<h1>ユーザー新規登録</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h4><%= @user.name %>のページ</h4>
<p>メールアドレス: <%= @user.email %></p>
<p>
  <%= link_to 'ユーザー情報を編集', edit_user_path(@user.id) %>
</p>
<p>
  <%= link_to 'ログアウト', session_path(current_user.id), method: :delete %>
</p>